language: ruby
rvm:
  - "2.1.0"
env:
  - "TEST_DB=rehttp_test TEST_DB_USER=rehttp"
before_script:
  - "psql -c 'create database rehttp_test;' -U postgres"
script: "bundle exec rspec spec"
before_install: "script/cibuild"
