language: ruby
rvm:
  - "2.1.0"
before_script:
  - psql -c 'create database rehttp_test;' -U postgres
script:
  - bundle exec rake db:test:prepare
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec spec/
before_install:
  - script/cibuild
