language: ruby
rvm:
  - "2.1.0"
env:
  - "TEST_DB=rehttp_test TEST_DB_USER=postgres"
before_script:
  - "psql -c 'create database rehttp_test;' -U postgres"
script: "bundle exec rake db:schema:load db:test:prepare spec"
before_install: "script/cibuild"
