defaults: &defaults
  adapter: postgresql
  encoding: unicode

development:
  <<: *defaults
  database: <%= ENV['DEVELOPMENT_DB'] %>

test:
  <<: *defaults
  database: <%= ENV['TEST_DB'] %>

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['PRODUCTION_DB'] %>
  pool: 5
  username: <%= ENV['PRODUCTION_DB_USER'] %>
  password: <%= ENV['PRODUCTION_DB_PASSWORD'] %>
