defaults: &defaults
  adapter: postgresql
  encoding: unicode

development:
  <<: *defaults
  database: <%= ENV['DEVELOPMENT_DB'] %>

test:
  <<: *defaults
  database: rehttp_test
  username: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['PRODUCTION_DB'] %>
  pool: 5
  username: <%= ENV['PRODUCTION_DB_USER'] %>
  password: <%= ENV['PRODUCTION_DB_PASSWORD'] %>
